version: '3.9'
services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - 5402:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345678"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db:/var/lib/postgresql/data